[build]
  command = "npm install && npm run start && cd sdfsdf && npm run web:build && npm run copy-redirects"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
